# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy to static host site

on: [workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Clone Source Repo
      uses: actions/checkout@v3

    - name: Clone Hosting Repo
      uses: actions/checkout@v3
      with:
        repository: untitledev-np/kimonokitchenibiza.com
        path: ./static-host

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '18.9.1'
        npm_version: '10.2.4'

    - name: Build project
      run: |
        npm install
        npm run generate
        cp static-host/CNAME ./dist/
        # touch ./dist/.nojekyll
        date > ./dist/time.txt
        find ./dist/
        # cat ./dist/index.html

    - run: git config --unset-all http.https://github.com/.extraheader

    - name: Pushes to another repository
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@ssh-deploy-key
      env:
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
      with:
        source-directory: .output/public
        destination-github-username: 'untitledev-np'
        destination-repository-name: 'kimonokitchenibiza.com'
        user-email: sabingurung68@gmail.com
        commit-message: PIPELINE - deploying build static web site
        target-branch: master

